<Project Sdk="Microsoft.NET.Sdk.Worker">

	<PropertyGroup>
		<TargetFramework>net472</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<LangVersion>latest</LangVersion>
		
		<Version>1.7.0</Version>
		<AssemblyVersion>2.0.0.73</AssemblyVersion>
		<FileVersion>2.0.0.73</FileVersion>
		<InformationalVersion>1.2.2</InformationalVersion>
	</PropertyGroup>

	<ItemGroup>
	  <None Remove="InstaladorServicioTransmision.bat" />
	</ItemGroup>
	
	<ItemGroup>
		<PackageReference Include="Dapper" Version="2.1.66" />
		<PackageReference Include="Microsoft.Extensions.Hosting" Version="7.0.1" />
		<PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" Version="7.0.1" />
		<PackageReference Include="System.Data.SqlClient" Version="4.9.0" />
		<PackageReference Include="System.Data.SQLite" Version="1.0.119" />
	</ItemGroup>
	
	<ItemGroup>
	  <ProjectReference Include="..\AppBLL\Soltec.AppBLL.csproj" />
	  <ProjectReference Include="..\BLL\Soltec.BLL.csproj" />
	  <ProjectReference Include="..\Common\Soltec.Common.csproj" />
	  <ProjectReference Include="..\DAL\Soltec.DAL.csproj" />
	  <ProjectReference Include="..\Soltec.Common.LoggerFramework\Soltec.Common.LoggerFramework.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <Reference Include="Microsoft.CSharp" />
	  <Reference Include="System.Net.Http" />
	</ItemGroup>

	<ItemGroup>
	  <Content Update="appsettings.json">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </Content>
	</ItemGroup>

	<ItemGroup>
		<None Update="EliminaServicioTransmision.bat">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="IniciaServicioTensmision.bat">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="InstaladorServicioTransmisionBak.bat">
			<CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</None>
		<None Update="README.txt">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
	</ItemGroup>

	<Target Name="PostBuild" AfterTargets="PostBuildEvent">
		<Exec Command="&quot;C:\Program Files (x86)\Windows Kits\10\bin\10.0.22621.0\x64\signtool.exe&quot; sign ^&#xD;&#xA;/sha1 852f512ad44e0827e326406e3b44d7f109a68146 ^&#xD;&#xA;/fd SHA256 ^&#xD;&#xA;/td SHA256 ^&#xD;&#xA;/tr http://timestamp.digicert.com ^&#xD;&#xA;&quot;$(TargetPath)&quot;" />
	</Target>
</Project>
