<Project Sdk="Microsoft.NET.Sdk.Worker">

	<PropertyGroup>
		<TargetFramework>net472</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<LangVersion>latest</LangVersion>
		
		<Version>1.7.0</Version>
		<AssemblyVersion>2.0.0.50</AssemblyVersion>
		<FileVersion>2.0.0.50</FileVersion>
		<InformationalVersion>1.2.2</InformationalVersion>
	</PropertyGroup>

	<ItemGroup>
	  <None Remove="InstaladorServicioTransmision.bat" />
	</ItemGroup>
	
	<ItemGroup>
		<PackageReference Include="Microsoft.Extensions.Hosting" Version="7.0.1" />
		<PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" Version="7.0.1" />
	</ItemGroup>
	
	<ItemGroup>
	  <ProjectReference Include="..\AppBLL\Soltec.AppBLL.csproj" />
	  <ProjectReference Include="..\BLL\Soltec.BLL.csproj" />
	  <ProjectReference Include="..\Common\Soltec.Common.csproj" />
	  <ProjectReference Include="..\DAL\Soltec.DAL.csproj" />
	  <ProjectReference Include="..\Soltec.Common.LoggerFramework\Soltec.Common.LoggerFramework.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <Reference Include="System.Net.Http" />
	</ItemGroup>

	<ItemGroup>
	  <Compile Update="Properties\Settings.Designer.cs">
	    <DesignTimeSharedInput>True</DesignTimeSharedInput>
	    <AutoGen>True</AutoGen>
	    <DependentUpon>Settings.settings</DependentUpon>
	  </Compile>
	</ItemGroup>

	<ItemGroup>
	  <Content Update="appsettings.json">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </Content>
	</ItemGroup>

	<ItemGroup>
		<None Update="EliminaServicioTransmision.bat">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="IniciaServicioTensmision.bat">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="InstaladorServicioTransmisionBak.bat">
			<CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</None>
		<None Update="Properties\Settings.settings">
		  <Generator>SettingsSingleFileGenerator</Generator>
		  <LastGenOutput>Settings.Designer.cs</LastGenOutput>
		</None>
		<None Update="README.txt">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
	</ItemGroup>

	<Target Name="PostBuild" AfterTargets="PostBuildEvent">
		<Exec Command="if &quot;$(ConfigurationName)&quot; == &quot;Release&quot; (&#xD;&#xA;      xcopy &quot;$(TargetDir)*&quot; &quot;C:\sistemas\Releases\Soltec.WindowsServiceMonitorApps\service&quot; /E /I /Y&#xD;&#xA;)" />
	</Target>
</Project>
